// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type ModalStyles = "focusLock" | "root" | "small" | "medium" | "large" | "fullscreenOnMobile" | "footer" | "header" | "content" | "close" | "closeWithCircleBackground" | "closeIcon" | "hideOnFullscreen" | "spinnerContainer" | "footerSeparator" | "separator" | "rootWithShadow";
