// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type FlexStyles = "flex" | "alignStart" | "alignEnd" | "alignCenter" | "alignStretch" | "alignBaseline" | "justifyStart" | "justifyEnd" | "justifyCenter" | "justifyAround" | "justifyBetween" | "noWrap" | "wrap" | "wrapReverse" | "vertical" | "horizontal" | "flexCenter";
