// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type MarginStyles = "marginReset" | "marginTop4" | "marginBottom4" | "marginTop8" | "marginBottom8" | "marginTop20" | "marginBottom20" | "marginTop40" | "marginBottom40" | "marginTop60" | "marginCenterHorz" | "marginLeft8";
