// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type ProgressStyles = "progress" | "progressBar" | "animating" | "xxsmall" | "xsmall" | "small" | "large" | "indeterminate" | "indeterminateBar1" | "indeterminate1" | "indeterminateBar2" | "indeterminate2";
