// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type VoidTooltipStyles = "tooltip" | "tooltipDisablePointerEvents" | "tooltipPointer" | "tooltipContent" | "tooltipContentAllowOverflow" | "tooltipTop" | "tooltipBottom" | "tooltipCenter" | "tooltipLeft" | "tooltipRight" | "tooltipPrimary" | "tooltipGrey" | "tooltipBrand" | "tooltipRed" | "tooltipGreen" | "tooltipPointerBg";
