// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type AlertModalStyles = "container" | "form" | "modalContent" | "content" | "title" | "body" | "primaryButton" | "secondaryButton" | "modalFooter";
