// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type BaseRadioGroupStyles = "dotIn" | "fillIn" | "dotOut" | "fillOut" | "radioIndicator" | "innerDotRadio" | "outerRadioBase" | "outerRadioFill" | "radioGroupOption" | "standaloneRadioIndicator" | "animateIn" | "animateOut" | "group" | "radioItemIcon" | "label" | "container" | "outerRadioBorderStroke";
