// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type VoidRadioGroupStyles = "radioBar" | "radioPositionLeft" | "radioPositionRight" | "item" | "itemFilled" | "disabled" | "container" | "info" | "icon" | "radioIndicator" | "radioIndicatorGroup" | "refreshIcon" | "refreshIconStroke" | "refreshIconFill" | "radioIndicatorChecked" | "radioIndicatorDisabled";
