// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type SliderStyles = "slider" | "mini" | "bar" | "grabber" | "disabled" | "barFill" | "track" | "mark" | "markAbove" | "markBelow" | "markValue" | "markDash" | "markDashSimple" | "defaultValue" | "hasMarks";
