// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type ShinyButtonStyles = "shinyButton" | "buttonShine" | "Shine" | "onlyShineOnHover" | "InstantShine" | "shineContainer" | "shine" | "shineDefault" | "shineSmall" | "shinePaused" | "shineInner" | "shineInnerDefault" | "shineInnerSmall";
