// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type TextInputStyles = "inputWrapper" | "input" | "focused" | "error" | "disabled" | "editable" | "inputDefault" | "inputMini" | "inputPrefix" | "inputError";
