// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type QuickSelectStyles = "quickSelect" | "quickSelectClick" | "quickSelectValue" | "quickSelectLabel" | "quickSelectArrow" | "quickSelectPopout" | "quickSelectPopoutScroll" | "quickSelectScroller" | "quickSelectPopoutOption";
