// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type BlobMaskStyles = "wrapper" | "svg" | "shiftSVG" | "noContain" | "lowerBadge" | "scaleIn" | "scaleInHeight" | "badgeStroke" | "isHighlighted" | "upperBadge" | "focusStroke" | "focusFill" | "highlight";
