// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type FormTextStyles = "formText" | "default" | "labelDescriptor" | "labelSelected" | "placeholder" | "labelBold" | "description" | "modeDefault" | "modeSelectable" | "modeDisabled" | "error" | "success";
