// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type FormErrorBlockStyles = "error" | "icon" | "text" | "backgroundRed" | "errorClose" | "errorCloseIcon" | "backgroundTertiary" | "backgroundAccent";
