// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type ScrollerStyles = "scrollerBase" | "auto" | "none" | "thin" | "customTheme" | "fade" | "scrolling" | "content" | "disableScrollAnchor" | "managedReactiveScroller" | "pointerCover";
