// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type LayerStyles = "layerContainer" | "clickTrapContainer" | "trapClicks" | "layer" | "emptyError" | "layerHidden" | "disabledPointerEvents";
