// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type PaginatorStyles = "pageControlContainer" | "pageControl" | "pageButton" | "roundButton" | "endButton" | "endButtonInner" | "gap" | "iconCaret" | "jumpToPageInlineInput" | "activeButton";
