// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type ListBoxStyles = "listBox" | "scrollable" | "listBoxItem" | "listBoxItemContent" | "inInput" | "listBoxItemLabel" | "selectedIcon" | "loadingSpinnerWrapper" | "loadingSpinner" | "loadingSpinnerInner";
