// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type BaseCheckboxStyles = "bgFill" | "bgEmpty" | "dotGrow" | "dotShrink" | "checkDraw" | "checkUndraw" | "checkboxItem" | "padding" | "checkboxIndicator" | "backgroundFill" | "checkStroke" | "checkmark" | "dot" | "animateOut" | "leadingIcon" | "label" | "labelContent" | "labelContainer" | "animateIn";
