// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type BaseCheckboxStyles = "bgFill" | "bgEmpty" | "dotGrow" | "dotShrink" | "checkDraw" | "checkUndraw" | "checkboxItem" | "checkboxIndicator" | "backgroundFill" | "checkmark" | "checkStroke" | "dot" | "animateOut" | "leadingIcon" | "label" | "labelContent";
