// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type VoidCheckboxStyles = "checkboxWrapper" | "row" | "checked" | "inputDefault" | "checkboxWrapperDisabled" | "checkbox" | "alignTop" | "alignCenter" | "input" | "inputDisabled" | "inputReadonly" | "box" | "smallBox" | "round" | "checkboxDisabled" | "label" | "labelClickable" | "labelDisabled" | "labelForward" | "labelReversed";
