// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type BaseRadioGroupStyles = "dotIn" | "fillIn" | "dotOut" | "fillOut" | "radioIndicator" | "innerDotRadio" | "outerRadioFill" | "item" | "outerRadioBorderStroke" | "outerRadioBase" | "animateOut" | "group" | "radioItemIcon" | "label" | "labelContent";
