// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type BaseRadioGroupStyles = "group" | "item" | "radioIndicator" | "outerRadioFill" | "outerRadioBorderStroke" | "innerDotRadio" | "radioItemIcon";
