// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type RadioGroupStyles = "radioBar" | "radioPositionLeft" | "radioPositionRight" | "item" | "itemFilled" | "disabled" | "collapsibleItem" | "tooltipWrapper" | "info" | "icon" | "radioIndicator" | "radioIndicatorGroup" | "refreshIcon" | "refreshIconStroke" | "refreshIconFill" | "radioIndicatorChecked" | "radioIndicatorDisabled";
