// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type TabBarStyles = "header" | "item" | "headerText" | "brand" | "themed" | "separator" | "selected" | "disabled" | "side" | "top" | "topPill" | "destructive";
