// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type PopoverCaretStyles = "caret" | "caret--bottom" | "caret--top" | "caret--left" | "caret--right" | "caret--center" | "caret--start" | "caret--end" | "caret--custom";
