// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type AvatarStyles = "wrapper" | "pointer" | "mask" | "svg" | "cursorDefault" | "avatarStack" | "avatar" | "avatarLatched" | "avatarSpeaking" | "pointerEvents" | "avatarDecoration" | "cutoutIcon" | "largeEmoji";
