// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type BadgesStyles = "eyebrow" | "base" | "textBadge" | "baseShapeRound" | "baseShapeRoundLeft" | "baseShapeRoundRight" | "iconBadge" | "numberBadge" | "icon" | "circleBadge" | "premiumBadge";
