// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type SearchBarStyles = "container" | "inner" | "disabled" | "input" | "small" | "medium" | "large" | "iconLayout" | "pointer" | "iconContainer" | "icon" | "visible" | "clear";
