// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type FieldStyles = "container" | "labelContainer" | "control" | "helperTextContainer" | "description" | "icon" | "label" | "required" | "slideDown" | "statusMessageContainer" | "badgeContainer";
