// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type FormControlStyles = "container" | "labelContainer" | "control" | "helperTextContainer" | "icon" | "description" | "label" | "required" | "slideDown" | "statusMessageContainer" | "badgeContainer";
