// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type GraphicStyles = "container" | "aspect-ratio-21/9" | "aspect-ratio-16/9" | "aspect-ratio-6/4" | "aspect-ratio-2/1" | "aspect-ratio-1/1" | "image" | "video" | "lottie" | "rive";
