// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type SelectStyles = "selectFieldContainer" | "fullWidth" | "selectField" | "isInert" | "isFocused" | "selectButton" | "multipleValues" | "placeholder" | "chevronButton" | "chevronIcon" | "isOpen" | "clearButton";
