// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type BreadcrumbsStyles = "breadcrumbs" | "breadcrumbWrapper" | "activeBreadcrumb" | "breadcrumbClickWrapper" | "breadcrumbFinalWrapper" | "breadcrumb" | "breadcrumbArrow" | "interactiveBreadcrumb";
