// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type ColorPickerStyles = "container" | "gradient" | "customContainer" | "defaultContainer" | "custom" | "customColorPicker" | "colorPickerRow" | "colorPickerSwatch" | "default" | "gradientPreset" | "disabled" | "colorPickerDropper" | "suggestedColors" | "suggestedColor" | "noColor";
