// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type CopyInputStyles = "copyInput" | "copyInputDefault" | "copyInputError" | "copyInputSuccess" | "layout" | "inputWrapper" | "button" | "hiddenMessage" | "input" | "inputDefault" | "inputError" | "inputSuccess" | "inputHidden";
