// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type ComboboxStyles = "combobox" | "list" | "scroller" | "item" | "focused" | "disabled" | "itemLabel" | "itemCheckbox" | "empty" | "selected" | "selectedBrand" | "searchWithScrollbar";
