// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type PopoutCSSAnimatorStyles = "translate" | "animatorTop" | "animatorBottom" | "animatorLeft" | "animatorRight" | "animatorCenter" | "didRender" | "scale" | "fade";
