// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type SegmentedControlStyles = "tabItem" | "tabContainer" | "pillContainer" | "pillItem" | "pillItemSelected" | "tabItemSelected" | "icon" | "controlText" | "pillItemText" | "disabled" | "disabledContainer";
