// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type KeyComboStyles = "combo" | "key" | "bindArrow" | "up" | "left" | "right" | "dim" | "keybindShortcutSearchPopout" | "keyboardShortcuts";
