// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY
export type ImageStyles = "imageWrapper" | "clickableWrapper" | "loadingOverlay" | "imageWrapperBackground" | "imagePlaceholder" | "imageErrorWrapper" | "imageError" | "imageLoadingOverlay" | "cornerLoadingSpinner" | "imageAccessory" | "imageZoom" | "clickable" | "originalLink";
